### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by muddy-alex** [bcgov-nr/action-pr-description-add#129]
This action has been working great for a few months, however, recently we are starting to consistently see the following error.

```
/usr/bin/docker exec  d78cf9dd0e6b64b726fb55d93c5984076348657532e98bdb8eb086236e699657 sh -c "cat /etc/*release | grep ^ID"
HttpError: Resource not accessible by integration
    at /__w/_actions/bcgov-nr/action-pr-description-add/v0.0.2/webpack:/typescript-action/node_modules/@octokit/request/dist-node/index.js:[8](https://github.com/xxxx/xxxx/actions/runs/4700283625/jobs/8334757870?pr=159#step:6:9)6:1
    at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/xxxx/xxxx/actions/runs/4700283625/jobs/8334757870?pr=159#step:6:10)6:5)
```

**Comment by DerekRoberts** [comment]
Hi @muddy-alex! Thanks for the report. To make troubleshooting easier can you point me to a repo having this issue?

**Comment by muddy-alex** [comment]
This does fix the issues we are having. Unfortunately, the repository is private so I cant share it.

I can provide a redacted version of the pipeline, however :)

```
 update-asana:
    needs: <SOME ID>
    runs-on: ubuntu-latest
    container:
      image: <OUR CUSTOM BUILD IMAGE>
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - <CALL A REST API AND WRITE TO PIPELINE OUTPUT>

      - uses: bcgov-nr/action-pr-description-add@v0.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_markdown: |
            <INJECT LINK TO ASANA TICKET>
```
